### ISSUE TITLE
Json.NET 8.0.3

### ISSUE THREAD

**Issue by matthewct** [vtfuture/RequireJSDotNet#71]
We are using Json.NET 8.0.3 in our Visual Studio 2012 (Update 5) project as it is required by another package but we get the following compile error:

"Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified."

The output shows the following:

"\.build\Compressor.targets(7,5): error : Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified."

We would just like to know when RequireJSDotNet would be updated to Json.NET 8.0.3 ?

Thank you in advance for any help you can provide.

**Comment by praneetloke** [comment]
Wouldn't this be solved with an assembly binding redirect in your project for 7.x to 8.x?

**Comment by matthewct** [comment]
We have the following binding redirect but this did not fix the problem:

<dependentAssembly>
<assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
<bindingRedirect oldVersion="0.0.0.0-8.0.0.0" newVersion="8.0.0.0" />
</dependentAssembly>

We ended up having to update the RequireJSDotNet projects to Json.NET 8.0.3 and then created a local Nuget package.

**Comment by praneetloke** [comment]
There seems to be a known problem with unit test projects in VS 2012 not caring about bindingRedirect in app.config files. Does [this](https://social.msdn.microsoft.com/Forums/vstudio/en-US/ba271f86-ed33-49a5-9b52-99980e88d198/problem-with-assembly-version-redirection-in-appconfig-not-working-in-unit-tests-in-vs2012?forum=vsunittest) apply to you? It's just odd that a binding redirect did not fix the problem for you.

**Comment by ddombrowskii** [comment]
@matthewct, I have the exact same problem, would it be possible for you to share the nuget package that you created ?

**Comment by matthewct** [comment]
@praneetloke
We have not revisited the possible binding redirect issues with VS 2012 after creating local Nuget packages. This is something we will have to look at if this issue occurs again but we may be moving to a newer VS version at some stage. Thanks for your help and comments, much appreciated.

@ddombrowskii
Attached are the following two RequireJS.NET Nuget packages in "RequireJsNet.zip" which we build to resolve this problem for now, but please note that the version numbers are for our use only:

RequireJsNet.Compressor.2.6.1.nupkg
RequireJsNet.2.6.0.nupkg

Download:
[RequireJsNet.zip](https://github.com/vtfuture/RequireJSDotNet/files/290198/RequireJsNet.zip)

**Comment by stefanprodan** [comment]
Fixed in release [2.2](https://github.com/vtfuture/RequireJSDotNet/releases/tag/v2.2.3)
